 ## Pertemuan 4

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\Octaffia\\anaconda3\\envs\\hacktiv8\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
[
    [1,2,3],
    [4,5,6]
]
# this is a 2x3 matrix
# yg ke bawah row, ke samping kolom

[[1, 2, 3], [4, 5, 6]]

di numpy istilahnya namanya axes, jika:
axes = 0 -> baris
axes = 1 -> kolom

### membuat array

In [10]:
x = [1,2,3]
x

[1, 2, 3]

In [8]:
x_np = np.array(x)

In [9]:
x_np

array([1, 2, 3])

In [11]:
z = np.zeros(6)

In [12]:
z

array([0., 0., 0., 0., 0., 0.])

In [14]:
y = np.ones(6)
y

array([1., 1., 1., 1., 1., 1.])

In [15]:
emptyarr = np.empty(6)
emptyarr

array([1., 1., 1., 1., 1., 1.])

In [17]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [18]:
arr = np.arange(2,10,3)
arr

array([2, 5, 8])

In [19]:
for i in np.arange(-10,12,2):
    print(i)

-10
-8
-6
-4
-2
0
2
4
6
8
10


### ADD, REMOVE, SORT

In [20]:
arr1 = np.array([1,2,3,4,5])

In [22]:
#add
np.append(arr1,6)

array([1, 2, 3, 4, 5, 6])

In [23]:
# bisa untuk memerge array
xxx = np.array([1,2])
yyy = np.array([3,4])
np.append(xxx,yyy)

array([1, 2, 3, 4])

In [24]:
# delete 
np.delete(arr1,1)
# di hapus berdasar index

array([1, 3, 4, 5])

In [25]:
arr2 = np.array([3,6,1,8,0,2,7,4])

In [26]:
np.sort(arr2)

array([0, 1, 2, 3, 4, 6, 7, 8])

### Shape and Size

In [27]:
arr2

array([3, 6, 1, 8, 0, 2, 7, 4])

In [28]:
arr2.shape

(8,)

In [41]:
new = [
    [[1,2,3]],
[[4,5,6]]
]
x = np.array(new)

In [42]:
x.shape #shape atribut

(2, 1, 3)

### RESHAPE

In [44]:
misal = np.arange(6)

In [45]:
np.reshape(misal,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
# bisa juga langsung
misal.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
# hasil kali tuple reshape((tup,le)) harus 
#sama dengan size
misal.size


6

In [54]:
#contoh penggunaan reshape
#dataset untuk train gambar
# 100 gambar, 128*128, dengan RGB (3 layer)
# jika di reshape maka
# 100,3,128,128
#jadi yang di reshape :
# 100, (128*128*3)

### convert 2d ke 3d

In [55]:
misal1 = np.arange(0,6)

In [56]:
misal1.shape

(6,)

In [59]:
# bisa aja pake reshape
np.reshape(misal1,(1,6)).shape

(1, 6)

In [58]:
# pake newaxis
misal1[np.newaxis].shape
# model 1 row 6 col

(1, 6)

In [60]:
misal1[:,np.newaxis].shape
# model 6 row, 1 col

(6, 1)

In [61]:
#terminologi

# row = jumlah data
# column = jumlah feature

In [62]:
np.expand_dims(misal1,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [63]:
np.expand_dims(misal1,axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [66]:
sample = np.array([1,2,3,4]).reshape((2,2))

In [67]:
sample.shape

(2, 2)

In [68]:
np.expand_dims(sample,axis=0).shape

(1, 2, 2)

### indexing dan slicing

In [69]:
misal2 = np.array([1,2,3,4,5])
misal2

array([1, 2, 3, 4, 5])

In [71]:
misal2[2:]

array([3, 4, 5])

In [74]:
misal2[-4:]

array([2, 3, 4, 5])

In [75]:
misal2[2:4]

array([3, 4])

In [76]:
misal2[:3]

array([1, 2, 3])

In [77]:
#SLicing 2D ke atas tinggal mainin logic aja

In [78]:
# slicing dengan kondisi
misal2[misal2>2] #bisa multiple, bisa mod

array([3, 4, 5])

In [88]:
# slicing dengan kondisi

misal2[(misal2 % 2 == 0)&(misal2 > 2)] #bisa multiple, bisa mod

array([4])

In [89]:
misal3 = np.array([1,2,3])
misal4 = np.array([4,5,6])


In [91]:
np.vstack((misal3,misal4)) #add 2 array jadi berbentuk sekian dimensi

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
np.vstack((misal3,misal4)).shape #add 2 array jadi berbentuk sekian dimensi

(2, 3)

In [93]:
np.hstack((misal3,misal4)) #add 2 array jadi berbentuk sekian dimensi

array([1, 2, 3, 4, 5, 6])

In [94]:
#hsplit
misal5 = np.array([1,2,3,4,5,6])
np.hsplit(misal5,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [95]:
# .view() = pass by variable
# .copy() udah gaada hubungan sama yg awal

### array operation

In [97]:
a = np.array([[1,2],[2,3]])
b = np.array([[3,1],[2,1]])

In [98]:
a + b

array([[4, 3],
       [4, 4]])

In [99]:
#hadamard product
a * b

array([[3, 2],
       [4, 3]])

In [100]:
a / b 

array([[0.33333333, 2.        ],
       [1.        , 3.        ]])

In [101]:
adata =  np.array([[1,2,3],
                  [3,4,5],
                  [4,5,6]])
adata.sum(axis=1)

array([ 6, 12, 15])

In [102]:
adata.sum(axis=0)

array([ 8, 11, 14])

In [103]:
adata.mean(axis=0)

array([2.66666667, 3.66666667, 4.66666667])

In [105]:
np.median(adata,axis=0)

array([3., 4., 5.])

In [108]:
adata + np.ones(3)

array([[2., 3., 4.],
       [4., 5., 6.],
       [5., 6., 7.]])

### Broadcasting

In [109]:
adata *2

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 8, 10, 12]])

### max-min 


In [110]:
adata.max(axis=0)

array([4, 5, 6])

In [111]:
adata.min(axis=0)

array([1, 2, 3])

In [112]:
adata.max(axis=1)

array([3, 5, 6])

In [113]:
adata.min(axis=1)

array([1, 3, 4])

In [114]:
adata.max()

6

In [115]:
adata.min()

1

### matrix

In [116]:
# dot prodak
a2 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[4,5,6],[7,8,9]])

In [117]:
np.dot(a2,b2.T)

array([[ 32,  50],
       [ 77, 122]])

In [119]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
a2.shape

(2, 3)

In [123]:
a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [125]:
a2.ravel() #sama kek flatten

array([1, 2, 3, 4, 5, 6])

In [ ]:
# terapin formula pake numpy


In [131]:
# transpose

a3 = np.random.rand(3)
a3

array([0.60599619, 0.51377862, 0.61018576])

In [132]:
a3.T

array([0.60599619, 0.51377862, 0.61018576])

In [134]:
#harusnya tidak begitu
# supaya aman maka : 
a3 = np.random.rand(3,1)
a3

array([[0.91743384],
       [0.75758676],
       [0.32725359]])

In [135]:
a3.T

array([[0.91743384, 0.75758676, 0.32725359]])

### Exercise

In [137]:
# 1
def RGB(n):
    return np.random.rand(3,n,n)
RGB(2)

array([[[0.88611307, 0.46774694],
        [0.93112854, 0.59478471]],

       [[0.3009755 , 0.63291496],
        [0.25695327, 0.50413081]],

       [[0.16810179, 0.9996475 ],
        [0.13952038, 0.54320708]]])

In [145]:
# 2
def rubik(n):
    return np.random.rand(n,n,n)
rubik(4)

array([[[0.23432789, 0.85723733, 0.12901274, 0.18106884],
        [0.15518059, 0.35684953, 0.88811002, 0.14742485],
        [0.73930031, 0.87257323, 0.96348127, 0.40008957],
        [0.58634127, 0.69131176, 0.84183426, 0.33547534]],

       [[0.6711271 , 0.82213475, 0.42670432, 0.42235502],
        [0.76638696, 0.73331151, 0.79161703, 0.02543504],
        [0.12510717, 0.27150845, 0.88236135, 0.67468755],
        [0.96295869, 0.2005726 , 0.51163673, 0.03024722]],

       [[0.82561065, 0.24779446, 0.45241903, 0.78392934],
        [0.09177554, 0.66125397, 0.20088984, 0.01253485],
        [0.92191572, 0.76646121, 0.42927416, 0.38387282],
        [0.7082336 , 0.8439124 , 0.18344154, 0.4919253 ]],

       [[0.88282666, 0.31297022, 0.51455503, 0.7649983 ],
        [0.12978137, 0.42540052, 0.81003018, 0.18994989],
        [0.27589846, 0.18829717, 0.18697856, 0.49114569],
        [0.37628615, 0.48608277, 0.00592796, 0.52789602]]])

In [142]:
# 3
def split(n):
    train = n[:round(.8*len(n))]
    test = n[round(.8*len(n)):]
    return train,test

data = np.random.rand(100,2)
t1,t2 = split(data)

In [143]:
t1.shape

(80, 2)

In [144]:
t2.shape

(20, 2)

In [176]:
def mse(n):
    axx = np.array([])
    for i in range(len(n)):
        np.append(axx,np.square(n[i,0]-n[i,1]))
    print(axx)
    return (1/n) * np.sum(axx)

In [177]:
a = np.random.rand(10,2)
b = 0
mse(a)

[]


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [167]:
b

array([[0., 0.],
       [0., 0.]])

In [158]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [159]:
a[1,1]

4